default_language_version:
    python: python3.13
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: detect-private-key
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: check-toml
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.6
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
          - id: ruff-format
